server:
  port: ${PORT:8080}

spring:
  application:
    name: Fei-Heroku-Spring-Test
  profiles:
    active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://x71wqc4m22j8e3ql.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/p4moo73z7rmvvoer}
    username: ${SPRING_DATASOURCE_USERNAME:cyfyazp2s556ox8w}
    password: ${SPRING_DATASOURCE_PASSWORD:en7ijotse26c0775}
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: false
      validation-query: select 1
      validation-query-timeout: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 180000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
  redis:
#    host: 39.100.78.62
#    host: redis://ec2-44-205-222-104.compute-1.amazonaws.com
#    port: 10640
#    password: p330b682b828e5234c8f003145a043b490c53485b82c18a8068c2a7512e1ae6d3
#    uri: redis://:p330b682b828e5234c8f003145a043b490c53485b82c18a8068c2a7512e1ae6d3@ec2-44-205-222-104.compute-1.amazonaws.com:10640
    database: 0
    timeout: 60000
    url: rediss://:p330b682b828e5234c8f003145a043b490c53485b82c18a8068c2a7512e1ae6d3@ec2-44-205-222-104.compute-1.amazonaws.com:10640

  cloud:
    consul:
      host: 39.100.78.62
      #host: 127.0.0.1
      port: 8500
      discovery:
        preferIpAddress: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}:@project.version@
        healthCheckPath: /actuator/health

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework: INFO
